### PR TITLE
fix: anki-editor--build-fields

### PR DESCRIPTION
**Pull request by cmirdesouza**
Possible solution to #7 

I only did implement the solution on [this](https://github.com/leoc/anki-editor/pull/1#issue-837589574)

I did not test it, if someone can test it or explain to me how I test it in my emacs, I use doom-emacs.

### CODE REVIEW

**Comment by orgtre** [comment]
Thanks. To test it load your fork of anki-editor instead of mine. With straight.el it would be something like 
```elisp
(use-package anki-editor  
  :straight (:host github :repo "cmirdesouza/anki-editor"))
```
Doom's package manager is built on straight.el so something like this should be possible. Normally to create a pull request I'd 1) create a fork using the Github UI, 2) load that fork like above, 3) make edits to the source in Emacs (which can be found using `M-x find-library anki-editor` in this case), 4) test everything as I do so, 5) commit and push the changes to my fork using magit (or git in command line), 6) submit the pull request via Github UI.

**Comment by cmirdesouza** [comment]
Thanks for the instructions, i'm going to test it and submit my findings.

**Comment by cmirdesouza** [comment]
Ooops kkkkkkk, my bad.

**Comment by orgtre** [comment]
OK, since it was a minor fix, the fastest was to just create a new commit and push it myself. Otherwise you'd have had to rebase your master branch somehow or create a new pull request, which is not something I can do for you. Thanks for the help and keep up learning!

**Comment by cmirdesouza** [comment]
Thanks for the teachings and the patience

**Pull request closed without merging**
